---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: lb-notifications

replicas:
  - name: sync-provider-users
    count: 2

images:
  - name: ghcr.io/lb-conn/lb-notifications/sync-provider-users
    newTag: "bd4ab9e1"

patches:
  # ConfigMap patch for environment-specific values
  - target:
      kind: ConfigMap
      name: shared-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: production
      - op: replace
        path: /data/PULSAR_URL
        value: pulsar+ssl://pc-e5e06aff.aws-sae1-staging-ij2t2.aws.snio.cloud:6651
      - op: replace
        path: /data/TEMPORAL_HOST_PORT
        value: temporal.prd-infra-temporal.svc.cluster.local:7233
      - op: replace
        path: /data/PULSAR_URL_ADMIN
        value: https://pc-e5e06aff.aws-sae1-staging-ij2t2.aws.snio.cloud:443

  # Deployment patches
  - target:
      kind: Deployment
      name: sync-provider-users
    patch: |-
      - op: replace
        path: /spec/template/spec/imagePullSecrets/0/name
        value: regcred

  # External Secret patch
  - target:
      kind: ExternalSecret
      name: lb-notifications-shared-secret
    patch: |-
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: /lb-notifications/prd/manual-secrets

