---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - shared-configmap.yaml
  - shared-external-secret.yaml
  - shared-secret.yaml
  - sync-provider-users-deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: lb-notifications

