---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: lb-notifications

replicas:
  - name: sync-provider-users
    count: 1

images:
  - name: ghcr.io/lb-conn/lb-notifications/sync-provider-users
    newTag: "bd4ab9e1"

patches:
  # ConfigMap patch for environment-specific values
  - target:
      kind: ConfigMap
      name: shared-config
    patch: |-
      - op: add
        path: /data/APP_ENV
        value: development
      - op: add
        path: /data/TEMPORAL_HOST_PORT
        value: temporal-frontend.temporal.svc.cluster.local:7233
      - op: add
        path: /data/PULSAR_URL
        value: pulsar://pulsar-broker.pulsar.svc.cluster.local:6650
      - op: add
        path: /data/PULSAR_URL_ADMIN
        value: http://pulsar-broker.pulsar.svc.cluster.local:8080
      - op: add
        path: /data/NOVU_API_URL
        value: http://novu.londonbridge.dev
      - op: add
        path: /data/NOVU_API_KEY
        value: 823c2695db4c59d7e1feef2790e797cd

  # Deployment patches
  - target:
      kind: Deployment
      name: sync-provider-users
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          role: dev
      - op: add
        path: /spec/template/metadata/labels/dev.londonbridge.service
        value: sync-provider-users

