---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: lb-notifications

replicas:
  - name: sync-provider-users
    count: 1

images:
  - name: ghcr.io/lb-conn/lb-notifications/sync-provider-users
    newTag: "ad796dc8"

patches:
  # ConfigMap patch for environment-specific values
  - target:
      kind: ConfigMap
      name: shared-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: development

  # Deployment patches
  - target:
      kind: Deployment
      name: sync-provider-users
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          role: dev
      - op: replace
        path: /spec/template/spec/imagePullSecrets/0/name
        value: regcred
      - op: add
        path: /spec/template/metadata/labels/dev.londonbridge.service
        value: sync-provider-users

  # External Secret patch
  - target:
      kind: ExternalSecret
      name: lb-notifications-shared-secret
    patch: |-
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: /lb-notifications/dev/manual-secrets

